defaults:
    - agent: ppo 
    - override hydra/launcher: joblib


hydra:
  launcher:
    n_jobs: 1
  sweep:
    dir: results/default_experiment
    subdir: ${hydra.job.override_dirname}/seed=${seed}
  job:
    config:
      override_dirname:
        kv_sep: "-"
        item_sep: "/"
        exclude_keys:
          - seed
          - gpu_ids


seed: 1
torch_deterministic: true
cuda: true
save_model: true
town: "Town03"
env_id: "carla-bev-v0"
num_envs: 1
num_steps: 256
total_timesteps: 1024
num_iterations: 0
gpu_ids: [0]
save_last_n: 2
save_video: true
num_vehicles: 25
p: 0.5
min_collision_scenes: 20
